<Project>
  <!-- Common Properties used by all assemblies -->
  <PropertyGroup>
    <LangVersion>10</LangVersion>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net8</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Company>ByteBard</Company>
    <PackageProjectUrl>https://github.com/ByteBardOrg/AsyncAPI.NET</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/ByteBardOrg/AsyncAPI.NET</RepositoryUrl>
    <PackageTags>asyncapi .net openapi documentation</PackageTags>
    <PackageIcon>logo.png</PackageIcon>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <!-- Optional: Publish the repository URL in the built .nupkg (in the NuSpec <Repository> element) -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <!-- Optional: Embed source files that are not tracked by the source control manager to the PDB -->
    <!-- This is useful if you generate files during the build -->
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <!-- Recommended: Embed symbols containing Source Link in the main file (exe/dll) -->
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\media\logo.png" Pack="true" PackagePath="\" />
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\..\LICENSE.txt" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>