//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByteBard.AsyncAPI {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ByteBard.AsyncAPI.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Validation_ChannelsMustBeUnique {
            get {
                return ResourceManager.GetString("Validation_ChannelsMustBeUnique", resourceCulture);
            }
        }
        
        internal static string Validation_EmailMustBeEmailFormat {
            get {
                return ResourceManager.GetString("Validation_EmailMustBeEmailFormat", resourceCulture);
            }
        }
        
        internal static string Validation_ExtensionNameMustBeginWithXDash {
            get {
                return ResourceManager.GetString("Validation_ExtensionNameMustBeginWithXDash", resourceCulture);
            }
        }
        
        internal static string Validation_OperationMustReferenceValidChannel {
            get {
                return ResourceManager.GetString("Validation_OperationMustReferenceValidChannel", resourceCulture);
            }
        }
        
        internal static string Validation_FieldRequired {
            get {
                return ResourceManager.GetString("Validation_FieldRequired", resourceCulture);
            }
        }
        
        internal static string Validation_MustBeNonNegative {
            get {
                return ResourceManager.GetString("Validation_MustBeNonNegative", resourceCulture);
            }
        }
        
        internal static string Validation_KeyMustMatchRegularExpr {
            get {
                return ResourceManager.GetString("Validation_KeyMustMatchRegularExpr", resourceCulture);
            }
        }
        
        internal static string Validation_MustBeAbsoluteUrl {
            get {
                return ResourceManager.GetString("Validation_MustBeAbsoluteUrl", resourceCulture);
            }
        }
        
        internal static string Validation_NameMustMatchRegularExpr {
            get {
                return ResourceManager.GetString("Validation_NameMustMatchRegularExpr", resourceCulture);
            }
        }
        
        internal static string Validation_SymbolsMustMatchRegularExpression {
            get {
                return ResourceManager.GetString("Validation_SymbolsMustMatchRegularExpression", resourceCulture);
            }
        }
        
        internal static string Validation_OperationMessagesMustReferenceOperationChannel {
            get {
                return ResourceManager.GetString("Validation_OperationMessagesMustReferenceOperationChannel", resourceCulture);
            }
        }
    }
}
