<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../Common.Build.props" />
  <PropertyGroup>
	  <Description>AsyncAPI.NET Bindings</Description>
	  <PackageId>ByteBard.AsyncAPI.NET.Bindings</PackageId>
	  <AssemblyName>ByteBard.AsyncAPI.Bindings</AssemblyName>
	  <RootNamespace>ByteBard.AsyncAPI.Bindings</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ByteBard.AsyncAPI.Readers\ByteBard.AsyncAPI.Readers.csproj" />
    <ProjectReference Include="..\ByteBard.AsyncAPI\ByteBard.AsyncAPI.csproj" />
  </ItemGroup>

</Project>
